# pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ft4"
version = "0.3.0"
requires-python = ">=3.10"
dependencies = [
  # PyTorch and Lightning are selected via an "extra":
  # uv sync --extra torch-cu128              # For CUDA 12.*
  # uv sync --extra torch-cpu                # For CPU
  # uv sync --extra torch-external --inexact # For already installed torch (outside of uv)

  "jsonargparse[signatures]>=4.41.0, <5.0.0", # Used by LightningArgumentParser
  "datasets>=4.0.0, <5.0.0", # HuggingFace datasets
  "heapdict>=1.0.1, <1.1.0", # Used by tokenizer
  "tqdm>=4.67.1, <5.0.0", # Progress bar
  "rich>=14.1.0, <15.0.0", # Rich progress bar
  "msgpack>=1.1.1, <1.2.0", # Serialize empirical model efficiently
]

[project.optional-dependencies]
# Choose exactly ONE of these:
torch-cpu = [
  "torch>=2.8.0, <2.9.0",
  "lightning>=2.5.4,<2.6.0",
]
torch-cu128 = [
  "torch>=2.8.0, <2.9.0",
  "lightning>=2.5.4,<2.6.0",
]
# For clusters / IT-managed installs using system torch:
torch-external = [
  "lightning>=2.5.4,<2.6.0"   # no torch here; use system torch
]
[tool.uv]
# Don’t allow mixing different backends
conflicts = [
  [{extra="torch-cpu"},     {extra="torch-cu128"}],
  [{extra="torch-external"},{extra="torch-cpu"}],
  [{extra="torch-external"},{extra="torch-cu128"}],
]
# Route torch to the right PyTorch index only when that extra is selected
[tool.uv.sources]
torch = [
  { index = "pytorch-cpu",   extra = "torch-cpu" },
  { index = "pytorch-cu128", extra = "torch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
# Define the PyTorch indexes
[[tool.uv.index]]
name = "pytorch-cpu"
url  = "https://download.pytorch.org/whl/cpu"
explicit = true
[[tool.uv.index]]
name = "pytorch-cu128"
url  = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
    "pytest>=8.4.2, <9.0.0",
    "pytest-watcher>=0.4.3",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pyright]
reportAttributeAccessIssue = false

[tool.pytest.ini_options]
markers = [
    "lab(name): test tied to a specific lab (e.g. 'unit1.lab1')",
    "needs_checkpoint: requires a pre-trained checkpoint on disk"
]
testpaths = ["tests"]
addopts = "--ignore=attic/"
   